-- ===========================================================================
-- What's Cooking? — complete schema
--
-- HOW TO USE
--   Supabase dashboard → SQL Editor → New query → paste this whole file → Run.
--   Safe to re-run: everything is create-if-not-exists or create-or-replace.
--
-- Generated by concatenating supabase/migrations/ in order. Edit the
-- migrations, not this file, then regenerate with:
--   tool/build_schema.sh
--
-- Verify afterwards with supabase/verify.sql.
-- ===========================================================================


-- ==================== 20260820000001_extensions_and_enums.sql ====================

-- ---------------------------------------------------------------------------
-- 0001 · Extensions and enumerated types
-- See docs/DATABASE.md §3
-- ---------------------------------------------------------------------------

create extension if not exists "pgcrypto";      -- gen_random_uuid()
create extension if not exists "pg_trgm";       -- trigram search on meal names

-- Enums are created defensively so the file can be re-run during setup.
do $$ begin
  create type meal_category as enum ('breakfast','lunch','dinner','snack','dessert');
exception when duplicate_object then null; end $$;

do $$ begin
  create type meal_type as enum ('breakfast','lunch','dinner','snack');
exception when duplicate_object then null; end $$;

do $$ begin
  create type difficulty as enum ('easy','medium','hard');
exception when duplicate_object then null; end $$;

do $$ begin
  create type household_role as enum ('owner','member');
exception when duplicate_object then null; end $$;

do $$ begin
  create type invite_status as enum ('pending','accepted','expired','revoked');
exception when duplicate_object then null; end $$;

do $$ begin
  create type vote_choice as enum ('like','pass');
exception when duplicate_object then null; end $$;

do $$ begin
  create type dietary_tag as enum (
    'vegetarian','vegan','pescatarian','halal','kosher',
    'gluten_free','dairy_free','nut_free','low_carb','keto'
  );
exception when duplicate_object then null; end $$;

-- Cuisine is check-constrained text rather than an enum: the catalogue will
-- gain cuisines over time, and altering an enum in production is far more
-- disruptive than editing a constraint (docs/DATABASE.md §3).

-- ==================== 20260820000002_core_tables.sql ====================

-- ---------------------------------------------------------------------------
-- 0002 · Profiles, households, membership, invites
-- See docs/DATABASE.md §4.1-4.4
--
-- profiles and households reference each other, so the circular foreign key is
-- added after both tables exist.
-- ---------------------------------------------------------------------------

create table if not exists profiles (
  id                    uuid primary key references auth.users(id) on delete cascade,
  display_name          text not null,
  avatar_url            text,
  active_household_id   uuid,
  onboarding_completed  boolean not null default false,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

comment on column profiles.active_household_id is
  'Current household context for every scoped write. Every user has at least a personal household, so this is never null after provisioning.';

create table if not exists households (
  id                uuid primary key default gen_random_uuid(),
  name              text not null,
  created_by        uuid not null references profiles(id) on delete cascade,
  -- True for the household auto-created at signup. Flipped to false when a
  -- partner is invited in.
  is_personal       boolean not null default true,
  default_budget    numeric(10,2),
  default_servings  smallint not null default 2 check (default_servings > 0),
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

do $$ begin
  alter table profiles
    add constraint profiles_active_household_fk
    foreign key (active_household_id) references households(id) on delete set null;
exception when duplicate_object then null; end $$;

create table if not exists household_members (
  id            uuid primary key default gen_random_uuid(),
  household_id  uuid not null references households(id) on delete cascade,
  user_id       uuid not null references profiles(id) on delete cascade,
  role          household_role not null default 'member',
  joined_at     timestamptz not null default now(),
  unique (household_id, user_id)
);

create table if not exists household_invites (
  id            uuid primary key default gen_random_uuid(),
  household_id  uuid not null references households(id) on delete cascade,
  -- 8 characters, ambiguous glyphs excluded: these get read aloud and typed.
  code          text not null unique check (code ~ '^[A-HJ-NP-Z2-9]{8}$'),
  created_by    uuid not null references profiles(id) on delete cascade,
  status        invite_status not null default 'pending',
  expires_at    timestamptz not null default (now() + interval '7 days'),
  accepted_by   uuid references profiles(id) on delete set null,
  created_at    timestamptz not null default now()
);

-- ==================== 20260820000003_meals_ingredients.sql ====================

-- ---------------------------------------------------------------------------
-- 0003 · Meals, ingredients and their relationship
-- See docs/DATABASE.md §4.5-4.7
-- ---------------------------------------------------------------------------

create table if not exists meals (
  id                    uuid primary key default gen_random_uuid(),
  name                  text not null check (length(trim(name)) > 0),
  description           text,
  image_url             text,
  cuisine               text not null check (
    cuisine in (
      'filipino','japanese','korean','chinese','thai','vietnamese',
      'italian','mexican','american','indian','mediterranean','other'
    )
  ),
  category              meal_category not null,
  difficulty            difficulty not null default 'easy',
  cooking_time_minutes  smallint not null check (cooking_time_minutes > 0),
  estimated_cost        numeric(10,2) not null check (estimated_cost >= 0),
  servings              smallint not null default 2 check (servings > 0),
  calories              integer check (calories is null or calories >= 0),
  -- Ordered array of step strings. Always read as a whole unit and never
  -- queried individually, so a child table would add a join for nothing.
  instructions          jsonb not null default '[]'::jsonb,
  dietary_tags          dietary_tag[] not null default '{}',
  tags                  text[] not null default '{}',
  is_public             boolean not null default false,
  created_by            uuid references profiles(id) on delete set null,
  household_id          uuid references households(id) on delete cascade,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),

  -- A meal is either in the public catalogue or private to one household.
  -- Never both, never neither.
  constraint meals_visibility_ck check (
    (is_public and household_id is null)
    or (not is_public and household_id is not null)
  )
);

create table if not exists ingredients (
  id            uuid primary key default gen_random_uuid(),
  name          text not null unique check (name = lower(trim(name))),
  category      text not null check (
    category in ('protein','vegetable','fruit','grain','dairy','spice','condiment','other')
  ),
  default_unit  text not null,
  -- Staples are assumed present and never reduce a pantry match percentage.
  -- Without this every meal caps near 80% and the number stops meaning
  -- anything (docs/USER_FLOWS.md §12).
  is_staple     boolean not null default false,
  created_at    timestamptz not null default now()
);

create table if not exists meal_ingredients (
  id             uuid primary key default gen_random_uuid(),
  meal_id        uuid not null references meals(id) on delete cascade,
  -- restrict, not cascade: silently emptying recipes is not an acceptable
  -- failure mode.
  ingredient_id  uuid not null references ingredients(id) on delete restrict,
  quantity       numeric(10,2) not null check (quantity > 0),
  unit           text not null,
  is_optional    boolean not null default false,
  unique (meal_id, ingredient_id)
);

-- ==================== 20260820000004_preferences.sql ====================

-- ---------------------------------------------------------------------------
-- 0004 · User preferences, favourites, dislikes
-- See docs/DATABASE.md §4.8-4.9
-- ---------------------------------------------------------------------------

create table if not exists user_preferences (
  id                    uuid primary key default gen_random_uuid(),
  user_id               uuid not null unique references profiles(id) on delete cascade,
  favorite_cuisines     text[] not null default '{}',
  disliked_ingredients  uuid[] not null default '{}',
  -- Applied as a hard filter by the recommendation engine, never a penalty.
  dietary_tags          dietary_tag[] not null default '{}',
  default_budget        numeric(10,2) check (default_budget is null or default_budget >= 0),
  max_cooking_time      smallint check (max_cooking_time is null or max_cooking_time > 0),
  preferred_servings    smallint not null default 2 check (preferred_servings > 0),
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

-- Favourites are visible to household members.
create table if not exists favorite_meals (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references profiles(id) on delete cascade,
  meal_id     uuid not null references meals(id) on delete cascade,
  created_at  timestamptz not null default now(),
  unique (user_id, meal_id)
);

-- Dislikes are strictly private. A partner seeing what you dislike is a social
-- cost with no product benefit; the engine reads both server-side regardless
-- (docs/ARCHITECTURE.md §8.3).
create table if not exists disliked_meals (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references profiles(id) on delete cascade,
  meal_id     uuid not null references meals(id) on delete cascade,
  created_at  timestamptz not null default now(),
  unique (user_id, meal_id)
);

-- ==================== 20260820000005_history_pantry_grocery.sql ====================

-- ---------------------------------------------------------------------------
-- 0005 · Meal history, pantry, grocery
-- See docs/DATABASE.md §4.10-4.12
-- ---------------------------------------------------------------------------

create table if not exists meal_history (
  id            uuid primary key default gen_random_uuid(),
  household_id  uuid not null references households(id) on delete cascade,
  meal_id       uuid not null references meals(id) on delete restrict,
  decided_by    uuid not null references profiles(id) on delete cascade,
  eaten_at      timestamptz not null default now(),
  meal_type     meal_type not null,
  actual_cost   numeric(10,2) check (actual_cost is null or actual_cost >= 0),
  source        text not null default 'roulette' check (
    source in ('roulette','manual','planner','ai')
  ),
  -- Cooked vs ordered. Feeds the statistics screen.
  was_cooked    boolean not null default true,
  created_at    timestamptz not null default now()
);

create table if not exists pantry_items (
  id               uuid primary key default gen_random_uuid(),
  household_id     uuid not null references households(id) on delete cascade,
  ingredient_id    uuid not null references ingredients(id) on delete cascade,
  -- Null means "we have some" without a tracked amount.
  quantity         numeric(10,2) check (quantity is null or quantity >= 0),
  unit             text,
  expiration_date  date,
  added_by         uuid references profiles(id) on delete set null,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  -- Adding an ingredient already present updates quantity rather than
  -- creating a duplicate row.
  unique (household_id, ingredient_id)
);

create table if not exists grocery_lists (
  id            uuid primary key default gen_random_uuid(),
  household_id  uuid not null references households(id) on delete cascade,
  name          text not null default 'Grocery List',
  is_active     boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- One active list per household.
create unique index if not exists grocery_lists_one_active_idx
  on grocery_lists (household_id) where is_active;

create table if not exists grocery_items (
  id                  uuid primary key default gen_random_uuid(),
  grocery_list_id     uuid not null references grocery_lists(id) on delete cascade,
  ingredient_id       uuid references ingredients(id) on delete set null,
  -- Free text matters: someone in a supermarket must be able to add
  -- "the good soy sauce" without our vocabulary approving it first.
  custom_name         text,
  quantity            numeric(10,2) check (quantity is null or quantity > 0),
  unit                text,
  is_completed        boolean not null default false,
  completed_by        uuid references profiles(id) on delete set null,
  completed_at        timestamptz,
  -- Provenance: lets the UI show why an item is on the list, and lets removing
  -- a planned meal clean up after itself.
  added_from_meal_id  uuid references meals(id) on delete set null,
  created_at          timestamptz not null default now(),

  constraint grocery_items_name_ck check (
    (ingredient_id is not null and custom_name is null)
    or (ingredient_id is null and custom_name is not null)
  )
);

-- ==================== 20260820000006_planner_voting.sql ====================

-- ---------------------------------------------------------------------------
-- 0006 · Meal plans (v1.3) and Can't Agree voting (v1.1)
-- See docs/DATABASE.md §4.13-4.14
--
-- Created now so the schema is complete and RLS is uniform. The features
-- themselves ship later.
-- ---------------------------------------------------------------------------

create table if not exists meal_plans (
  id            uuid primary key default gen_random_uuid(),
  household_id  uuid not null references households(id) on delete cascade,
  meal_id       uuid not null references meals(id) on delete cascade,
  planned_date  date not null,
  meal_type     meal_type not null,
  created_by    uuid not null references profiles(id) on delete cascade,
  created_at    timestamptz not null default now(),
  -- One meal per slot.
  unique (household_id, planned_date, meal_type)
);

create table if not exists vote_sessions (
  id                  uuid primary key default gen_random_uuid(),
  household_id        uuid not null references households(id) on delete cascade,
  -- Frozen on the session so both partners genuinely vote on the same meals.
  -- Regenerating per user would make a "match" meaningless.
  candidate_meal_ids  uuid[] not null check (array_length(candidate_meal_ids, 1) > 0),
  started_by          uuid not null references profiles(id) on delete cascade,
  resolved_meal_id    uuid references meals(id) on delete set null,
  created_at          timestamptz not null default now(),
  resolved_at         timestamptz
);

create table if not exists meal_votes (
  id          uuid primary key default gen_random_uuid(),
  session_id  uuid not null references vote_sessions(id) on delete cascade,
  user_id     uuid not null references profiles(id) on delete cascade,
  meal_id     uuid not null references meals(id) on delete cascade,
  choice      vote_choice not null,
  created_at  timestamptz not null default now(),
  unique (session_id, user_id, meal_id)
);

-- ==================== 20260820000007_functions_triggers.sql ====================

-- ---------------------------------------------------------------------------
-- 0007 · Functions and triggers
-- See docs/DATABASE.md §5
--
-- Every SECURITY DEFINER function sets search_path. Omitting it is a
-- privilege-escalation vector (docs/CODING_STANDARDS.md §11).
-- ---------------------------------------------------------------------------

-- --- Membership check -------------------------------------------------------
-- Household policies need to check membership, which queries
-- household_members, which evaluates the policy — infinite recursion.
-- SECURITY DEFINER bypasses RLS for the check itself and breaks the cycle
-- (docs/ARCHITECTURE.md §8.2).
create or replace function public.is_household_member(hid uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from household_members
    where household_id = hid and user_id = auth.uid()
  );
$$;

-- --- updated_at -------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
declare t text;
begin
  foreach t in array array[
    'profiles','households','meals','user_preferences',
    'pantry_items','grocery_lists'
  ] loop
    execute format('drop trigger if exists set_%1$s_updated_at on %1$s', t);
    execute format(
      'create trigger set_%1$s_updated_at before update on %1$s
       for each row execute function public.set_updated_at()', t);
  end loop;
end $$;

-- --- New user provisioning --------------------------------------------------
-- Creates the profile, its preferences, a personal household, the owner
-- membership, and points active_household_id at it — atomically.
--
-- This is why signup cannot leave a half-provisioned account, and why every
-- household-scoped table can have a NOT NULL household_id: there is no such
-- thing as a user without a household (docs/ARCHITECTURE.md §6.2).
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  new_household_id uuid;
  display text := coalesce(
    nullif(trim(new.raw_user_meta_data->>'display_name'), ''),
    split_part(coalesce(new.email, 'friend@example.com'), '@', 1)
  );
begin
  insert into profiles (id, display_name)
  values (new.id, display);

  insert into households (name, created_by, is_personal)
  values (display || '''s Kitchen', new.id, true)
  returning id into new_household_id;

  insert into household_members (household_id, user_id, role)
  values (new_household_id, new.id, 'owner');

  insert into user_preferences (user_id) values (new.id);

  update profiles
     set active_household_id = new_household_id
   where id = new.id;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- --- Invite code generation -------------------------------------------------
-- Excludes 0/O/1/I: these codes are read aloud and typed by hand.
create or replace function public.generate_invite_code()
returns text
language plpgsql
as $$
declare
  alphabet constant text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  result text := '';
  i int;
begin
  for i in 1..8 loop
    result := result || substr(alphabet, 1 + floor(random() * length(alphabet))::int, 1);
  end loop;
  return result;
end;
$$;

-- ==================== 20260820000008_indexes.sql ====================

-- ---------------------------------------------------------------------------
-- 0008 · Indexes
-- See docs/DATABASE.md §7. Each one is tied to a query it serves.
-- ---------------------------------------------------------------------------

-- Hit by every household RLS policy, in both directions.
create index if not exists household_members_user_idx      on household_members (user_id);
create index if not exists household_members_household_idx on household_members (household_id);

-- The recency query runs on every single spin and must never table-scan.
create index if not exists meal_history_recent_idx
  on meal_history (household_id, eaten_at desc);

-- Roulette filters.
create index if not exists meals_cuisine_idx      on meals (cuisine);
create index if not exists meals_category_idx     on meals (category);
create index if not exists meals_time_idx         on meals (cooking_time_minutes);
create index if not exists meals_cost_idx         on meals (estimated_cost);
create index if not exists meals_visibility_idx   on meals (is_public, household_id);

-- Array containment for dietary filters and mood tags.
create index if not exists meals_dietary_tags_idx on meals using gin (dietary_tags);
create index if not exists meals_tags_idx         on meals using gin (tags);

-- Meal search by name.
create index if not exists meals_name_trgm_idx    on meals using gin (name gin_trgm_ops);

-- Ingredient matching joins these across the catalogue. It is the heaviest
-- read in the app and the one most likely to regress; benchmarked in
-- Sprint 27.
create index if not exists meal_ingredients_meal_idx       on meal_ingredients (meal_id);
create index if not exists meal_ingredients_ingredient_idx on meal_ingredients (ingredient_id);

create index if not exists pantry_items_household_idx  on pantry_items (household_id);
create index if not exists grocery_items_list_idx      on grocery_items (grocery_list_id);
create index if not exists grocery_lists_household_idx on grocery_lists (household_id);

-- Scoring reads these on every spin.
create index if not exists favorite_meals_user_idx on favorite_meals (user_id);
create index if not exists disliked_meals_user_idx on disliked_meals (user_id);

create index if not exists meal_plans_household_date_idx on meal_plans (household_id, planned_date);
create index if not exists meal_votes_session_idx        on meal_votes (session_id);
create index if not exists household_invites_code_idx    on household_invites (code);

-- ==================== 20260820000009_rls_policies.sql ====================

-- ---------------------------------------------------------------------------
-- 0009 · Row Level Security
-- See docs/DATABASE.md §6 and docs/ARCHITECTURE.md §8
--
-- RLS is the security boundary, not client code. Deny by default: RLS is
-- enabled on every table, and no policy means no access.
--
-- Household-scoped tables all use public.is_household_member(), which is
-- SECURITY DEFINER and therefore does not recurse through these policies.
-- ---------------------------------------------------------------------------

alter table profiles           enable row level security;
alter table households         enable row level security;
alter table household_members  enable row level security;
alter table household_invites  enable row level security;
alter table meals              enable row level security;
alter table ingredients        enable row level security;
alter table meal_ingredients   enable row level security;
alter table user_preferences   enable row level security;
alter table favorite_meals     enable row level security;
alter table disliked_meals     enable row level security;
alter table meal_history       enable row level security;
alter table pantry_items       enable row level security;
alter table grocery_lists      enable row level security;
alter table grocery_items      enable row level security;
alter table meal_plans         enable row level security;
alter table vote_sessions      enable row level security;
alter table meal_votes         enable row level security;

-- --- profiles ---------------------------------------------------------------
drop policy if exists "read own profile" on profiles;
create policy "read own profile" on profiles
  for select using (id = auth.uid());

drop policy if exists "read household members profiles" on profiles;
create policy "read household members profiles" on profiles
  for select using (
    exists (
      select 1 from household_members hm
      where hm.user_id = profiles.id
        and public.is_household_member(hm.household_id)
    )
  );

drop policy if exists "update own profile" on profiles;
create policy "update own profile" on profiles
  for update using (id = auth.uid()) with check (id = auth.uid());

-- --- households -------------------------------------------------------------
drop policy if exists "members read household" on households;
create policy "members read household" on households
  for select using (public.is_household_member(id));

drop policy if exists "authenticated create household" on households;
create policy "authenticated create household" on households
  for insert with check (created_by = auth.uid());

drop policy if exists "owner updates household" on households;
create policy "owner updates household" on households
  for update using (
    exists (
      select 1 from household_members hm
      where hm.household_id = households.id
        and hm.user_id = auth.uid()
        and hm.role = 'owner'
    )
  );

-- --- household_members ------------------------------------------------------
drop policy if exists "members read membership" on household_members;
create policy "members read membership" on household_members
  for select using (public.is_household_member(household_id));

drop policy if exists "join household" on household_members;
create policy "join household" on household_members
  for insert with check (user_id = auth.uid());

-- Members may remove themselves; owners may remove anyone.
drop policy if exists "leave or remove member" on household_members;
create policy "leave or remove member" on household_members
  for delete using (
    user_id = auth.uid()
    or exists (
      select 1 from household_members owner
      where owner.household_id = household_members.household_id
        and owner.user_id = auth.uid()
        and owner.role = 'owner'
    )
  );

-- --- household_invites ------------------------------------------------------
drop policy if exists "members read invites" on household_invites;
create policy "members read invites" on household_invites
  for select using (public.is_household_member(household_id));

drop policy if exists "members create invites" on household_invites;
create policy "members create invites" on household_invites
  for insert with check (
    created_by = auth.uid() and public.is_household_member(household_id)
  );

drop policy if exists "members revoke invites" on household_invites;
create policy "members revoke invites" on household_invites
  for update using (public.is_household_member(household_id));

-- --- meals ------------------------------------------------------------------
drop policy if exists "read visible meals" on meals;
create policy "read visible meals" on meals
  for select using (
    is_public or public.is_household_member(household_id)
  );

drop policy if exists "create own meals" on meals;
create policy "create own meals" on meals
  for insert with check (
    created_by = auth.uid()
    and not is_public
    and public.is_household_member(household_id)
  );

drop policy if exists "update own meals" on meals;
create policy "update own meals" on meals
  for update using (created_by = auth.uid()) with check (created_by = auth.uid());

drop policy if exists "delete own meals" on meals;
create policy "delete own meals" on meals
  for delete using (created_by = auth.uid());

-- --- ingredients ------------------------------------------------------------
-- Shared vocabulary: readable by everyone signed in, append-only. Users must
-- never be blocked because our ingredient list is incomplete.
drop policy if exists "authenticated read ingredients" on ingredients;
create policy "authenticated read ingredients" on ingredients
  for select to authenticated using (true);

drop policy if exists "authenticated add ingredients" on ingredients;
create policy "authenticated add ingredients" on ingredients
  for insert to authenticated with check (true);

-- --- meal_ingredients -------------------------------------------------------
drop policy if exists "read ingredients of visible meals" on meal_ingredients;
create policy "read ingredients of visible meals" on meal_ingredients
  for select using (
    exists (
      select 1 from meals m
      where m.id = meal_ingredients.meal_id
        and (m.is_public or public.is_household_member(m.household_id))
    )
  );

drop policy if exists "manage ingredients of own meals" on meal_ingredients;
create policy "manage ingredients of own meals" on meal_ingredients
  for all using (
    exists (
      select 1 from meals m
      where m.id = meal_ingredients.meal_id and m.created_by = auth.uid()
    )
  );

-- --- user_preferences -------------------------------------------------------
-- Strictly private, with no household exception.
drop policy if exists "own preferences only" on user_preferences;
create policy "own preferences only" on user_preferences
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- --- favorite_meals ---------------------------------------------------------
-- Shared with household members, because couple scoring depends on it.
drop policy if exists "read household favourites" on favorite_meals;
create policy "read household favourites" on favorite_meals
  for select using (
    user_id = auth.uid()
    or exists (
      select 1 from household_members hm
      where hm.user_id = favorite_meals.user_id
        and public.is_household_member(hm.household_id)
    )
  );

drop policy if exists "manage own favourites" on favorite_meals;
create policy "manage own favourites" on favorite_meals
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- --- disliked_meals ---------------------------------------------------------
-- Strictly private. A partner seeing what you dislike is a social cost with no
-- product benefit; the engine reads both server-side regardless.
drop policy if exists "own dislikes only" on disliked_meals;
create policy "own dislikes only" on disliked_meals
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- --- household-scoped tables ------------------------------------------------
-- Identical shape everywhere, which is exactly what the personal-household
-- decision bought: no branch for "household or not".
drop policy if exists "household members read history" on meal_history;
create policy "household members read history" on meal_history
  for select using (public.is_household_member(household_id));

drop policy if exists "household members write history" on meal_history;
create policy "household members write history" on meal_history
  for insert with check (
    public.is_household_member(household_id) and decided_by = auth.uid()
  );

drop policy if exists "household members manage history" on meal_history;
create policy "household members manage history" on meal_history
  for delete using (public.is_household_member(household_id));

drop policy if exists "household members manage pantry" on pantry_items;
create policy "household members manage pantry" on pantry_items
  for all using (public.is_household_member(household_id))
  with check (public.is_household_member(household_id));

drop policy if exists "household members manage grocery lists" on grocery_lists;
create policy "household members manage grocery lists" on grocery_lists
  for all using (public.is_household_member(household_id))
  with check (public.is_household_member(household_id));

drop policy if exists "household members manage grocery items" on grocery_items;
create policy "household members manage grocery items" on grocery_items
  for all using (
    exists (
      select 1 from grocery_lists gl
      where gl.id = grocery_items.grocery_list_id
        and public.is_household_member(gl.household_id)
    )
  )
  with check (
    exists (
      select 1 from grocery_lists gl
      where gl.id = grocery_items.grocery_list_id
        and public.is_household_member(gl.household_id)
    )
  );

drop policy if exists "household members manage plans" on meal_plans;
create policy "household members manage plans" on meal_plans
  for all using (public.is_household_member(household_id))
  with check (public.is_household_member(household_id));

drop policy if exists "household members manage vote sessions" on vote_sessions;
create policy "household members manage vote sessions" on vote_sessions
  for all using (public.is_household_member(household_id))
  with check (public.is_household_member(household_id));

drop policy if exists "household members read votes" on meal_votes;
create policy "household members read votes" on meal_votes
  for select using (
    exists (
      select 1 from vote_sessions vs
      where vs.id = meal_votes.session_id
        and public.is_household_member(vs.household_id)
    )
  );

drop policy if exists "cast own votes" on meal_votes;
create policy "cast own votes" on meal_votes
  for insert with check (
    user_id = auth.uid()
    and exists (
      select 1 from vote_sessions vs
      where vs.id = meal_votes.session_id
        and public.is_household_member(vs.household_id)
    )
  );

-- ==================== 20260820000010_grants.sql ====================

-- ---------------------------------------------------------------------------
-- 0010 · Table privileges
--
-- RLS decides which *rows* a role may see. Grants decide whether the role may
-- touch the table at all. Both have to line up, and relying on Supabase's
-- default privileges leaves that implicit — so it is stated here.
--
-- This is defence in depth: if a future policy is written carelessly, the
-- grants still stop an anonymous key from reaching user data.
-- ---------------------------------------------------------------------------

grant usage on schema public to anon, authenticated;

-- Signed-in users may attempt anything; RLS constrains it to their own rows
-- and their household's.
grant select, insert, update, delete on all tables in schema public to authenticated;

alter default privileges in schema public
  grant select, insert, update, delete on tables to authenticated;

-- Anonymous access is limited to the public meal catalogue.
--
-- This is deliberate, not an oversight: guest mode lets someone spin before
-- creating an account (docs/PRD.md US-A-01), which needs the catalogue
-- readable without a session. The meals select policy already allows it via
-- `is_public`; revoking everything else means that even a careless future
-- policy cannot expose user data to an unauthenticated key.
revoke all on all tables in schema public from anon;
grant select on meals to anon;
grant select on meal_ingredients to anon;
grant select on ingredients to anon;

alter default privileges in schema public
  revoke all on tables from anon;

-- Functions callable by both roles. is_household_member is SECURITY DEFINER,
-- so it returns false rather than erroring when auth.uid() is null.
grant execute on function public.is_household_member(uuid) to anon, authenticated;
grant execute on function public.generate_invite_code() to authenticated;

-- ==================== 20260820000011_onboarding_dislikes.sql ====================

-- ---------------------------------------------------------------------------
-- 0011 · Free-text dislikes captured during onboarding
-- See docs/DATABASE.md §4.8
-- ---------------------------------------------------------------------------

-- user_preferences.disliked_ingredients holds ingredient ids, which is the
-- right long-term shape — the recommendation engine filters on ids, not on
-- strings a user typed. But onboarding runs before the ingredient catalogue
-- exists for that user's vocabulary: someone types "bagoong" or "cilantro" on
-- their first day and there may be no matching row, or no catalogue at all.
--
-- Dropping that input would be the wrong trade. Onboarding's stated rule is
-- that an abandoned run still leaves the app smarter than a blank one
-- (docs/USER_FLOWS.md §5), and a disliked food is the single most valuable
-- thing a user can tell us: it is a hard exclusion, not a preference weight.
--
-- So names are stored alongside ids rather than instead of them. When the
-- catalogue lands, a reconciliation pass resolves what it can into
-- disliked_ingredients and leaves the rest here as an unmatched record.
alter table user_preferences
  add column if not exists disliked_ingredient_names text[] not null default '{}';

comment on column user_preferences.disliked_ingredient_names is
  'Free-text foods the user said they avoid, as typed during onboarding. Resolved into disliked_ingredients once the ingredient catalogue can match them; unmatched entries stay here rather than being discarded.';

-- Guards the two ways this column degrades: an unbounded list, and blank
-- entries from a stray comma. Both are cheap to prevent and annoying to clean
-- up later.
do $$ begin
  alter table user_preferences
    add constraint user_preferences_disliked_names_sane check (
      array_length(disliked_ingredient_names, 1) is null
      or (
        array_length(disliked_ingredient_names, 1) <= 50
        and array_position(disliked_ingredient_names, '') is null
        and array_position(disliked_ingredient_names, null) is null
      )
    );
exception when duplicate_object then null; end $$;

-- ==================== 20260820000012_avatars_storage.sql ====================

-- ---------------------------------------------------------------------------
-- 0012 · Avatar storage
-- See docs/DATABASE.md §9
-- ---------------------------------------------------------------------------

-- A public bucket, deliberately. Avatars are shown to a household partner and
-- rendered by cached_network_image, and signing every request would mean a
-- round trip before a 44px circle can draw. Nothing private lives here.
--
-- "Public" governs reads only. Writes are still policy-controlled below: a
-- user can only write inside a folder named after their own id.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'avatars',
  'avatars',
  true,
  2097152,  -- 2 MB. A profile photo that needs more is a photo we should have
            -- resized on the client, and an unbounded bucket is a bill.
  array['image/jpeg','image/png','image/webp']
)
on conflict (id) do update
  set public             = excluded.public,
      file_size_limit    = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- Object paths are '<user_id>/avatar.<ext>'. storage.foldername() returns the
-- path segments, so element 1 is the owning user's id. Every write policy
-- checks it, which is what stops one user overwriting another's face.
do $$ begin
  create policy "avatars are readable by anyone"
    on storage.objects for select
    using (bucket_id = 'avatars');
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "a user writes only their own avatar"
    on storage.objects for insert to authenticated
    with check (
      bucket_id = 'avatars'
      and (storage.foldername(name))[1] = auth.uid()::text
    );
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "a user replaces only their own avatar"
    on storage.objects for update to authenticated
    using (
      bucket_id = 'avatars'
      and (storage.foldername(name))[1] = auth.uid()::text
    );
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "a user deletes only their own avatar"
    on storage.objects for delete to authenticated
    using (
      bucket_id = 'avatars'
      and (storage.foldername(name))[1] = auth.uid()::text
    );
exception when duplicate_object then null; end $$;

-- ==================== 20260820000013_delete_own_account.sql ====================

-- ---------------------------------------------------------------------------
-- 0013 · Account deletion
-- See docs/USER_FLOWS.md §17, docs/DATABASE.md §7
-- ---------------------------------------------------------------------------

-- Deleting a row from auth.users is privileged, and rightly so. The client
-- cannot be trusted with a key that could delete *anyone*, so the only key the
-- app ships is the publishable one, which cannot reach auth.users at all.
--
-- This function is the narrow exception: security definer, so it runs with the
-- owner's rights, but it takes no arguments and deletes only auth.uid(). There
-- is no parameter to tamper with, so there is no way to aim it at another
-- account. That property is the whole design - a delete_user(id uuid) variant
-- would be a privilege-escalation hole no matter how carefully it checked.
--
-- Everything else disappears by cascade: profiles.id references auth.users on
-- delete cascade, and every user-owned table cascades from profiles. Household
-- rows created by this user are removed with them; a partner's own rows are
-- not, which is what "the household retains its data" means in the flow.
create or replace function public.delete_own_account()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
begin
  if uid is null then
    raise exception 'delete_own_account requires an authenticated session'
      using errcode = '28000';
  end if;

  delete from auth.users where id = uid;
end;
$$;

comment on function public.delete_own_account is
  'Deletes the calling user and everything cascading from them. Takes no arguments by design: there is no id to tamper with, so it can only ever delete the caller.';

-- Only a signed-in user may call it. anon has no business here, and revoking
-- from public first means a future grant has to be deliberate.
revoke all on function public.delete_own_account() from public;
grant execute on function public.delete_own_account() to authenticated;

-- ==================== 20260820000014_public_meal_identity.sql ====================

-- ---------------------------------------------------------------------------
-- 0014 · A stable identity for catalogue meals
-- See docs/DATABASE.md §4.5 and §9 Q4
-- ---------------------------------------------------------------------------

-- The catalogue seed (supabase/seed/) has to be re-runnable: it is pasted into
-- the SQL Editor during setup, again when the catalogue grows, and again on any
-- fresh environment. Without a unique key on the public catalogue, a second run
-- would silently produce sixty duplicate meals, and the roulette would start
-- offering the same dish twice with two different ids.
--
-- `lower(name)` is that key, and it is a real catalogue invariant rather than a
-- convenience for the seed: two public meals with the same name are
-- indistinguishable to the person choosing between them. Distinguish them in
-- the name — "Chicken Adobo" and "Pork Adobo" — not in the id.
--
-- Partial, on `is_public`. Household-private custom meals (Sprint 26) are
-- deliberately excluded: two households may each name a meal "Mama's Adobo",
-- and neither can see the other's.
create unique index if not exists meals_public_name_uk
  on meals (lower(name))
  where is_public;

-- ==================== 20260821000015_meal_cost_per_serving.sql ====================

-- ---------------------------------------------------------------------------
-- 0015 · Cost per serving, as a column
-- See docs/DATABASE.md §4.5
-- ---------------------------------------------------------------------------

-- `estimated_cost` is for the servings the recipe states, so two meals at 300
-- pesos are not the same price if one feeds two people and the other feeds five.
-- Every place the app asks about budget asks per head: the onboarding question,
-- the profile setting, the discovery filter (Sprint 22) and the roulette's
-- budget constraint (Sprint 30).
--
-- A generated column rather than arithmetic at the call site. PostgREST can
-- filter and order on a column but not on an expression, so without this the
-- budget filter would have to fetch every candidate and divide in Dart — which
-- breaks pagination, because the server would no longer know how many rows
-- match.
--
-- Stored rather than virtual, so it can be indexed. `servings` is
-- check-constrained greater than zero, so there is no division by zero to guard.
alter table meals
  add column if not exists cost_per_serving numeric(10,2)
  generated always as (estimated_cost / servings) stored;

create index if not exists meals_cost_per_serving_idx
  on meals (cost_per_serving);
