#!/usr/bin/env bash
#
# Regenerates supabase/schema.sql by concatenating supabase/migrations/ in
# filename order.
#
# The migrations are the source of truth. schema.sql exists only so a fresh
# project can be set up with one paste into the Supabase SQL Editor, which is
# how supabase/README.md tells you to do it. Editing schema.sql by hand puts the
# two out of step, and the next run of this script silently discards the edit —
# so it is generated, never authored.
#
# The seed in supabase/seed/ is deliberately NOT included. Schema and data are
# applied at different times and for different reasons: a staging database gets
# the schema on every deploy and the catalogue once.
set -euo pipefail

cd "$(dirname "$0")/.."

out="supabase/schema.sql"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

cat >"$tmp" <<'HEADER'
-- ===========================================================================
-- What's Cooking? — complete schema
--
-- HOW TO USE
--   Supabase dashboard → SQL Editor → New query → paste this whole file → Run.
--   Safe to re-run: everything is create-if-not-exists or create-or-replace.
--
-- Generated by concatenating supabase/migrations/ in order. Edit the
-- migrations, not this file, then regenerate with:
--   tool/build_schema.sh
--
-- Verify afterwards with supabase/verify.sql.
-- ===========================================================================

HEADER

count=0
for migration in supabase/migrations/*.sql; do
  name="$(basename "$migration")"
  printf '\n-- ==================== %s ====================\n\n' "$name" >>"$tmp"
  cat "$migration" >>"$tmp"
  count=$((count + 1))
done

if [[ $count -eq 0 ]]; then
  echo "No migrations found — refusing to write an empty schema." >&2
  exit 1
fi

mv "$tmp" "$out"
trap - EXIT

echo "Wrote $out from $count migrations."
echo "Apply it, then run supabase/verify.sql. Every row must read PASS."
