#!/usr/bin/env bash
# Regenerates supabase/schema.sql from supabase/migrations/.
#
# schema.sql is what a new database gets pasted into the SQL Editor, so it has
# to be the migrations concatenated in filename order and nothing else. Written
# as a script rather than done by hand because the two drifting apart is silent:
# the app keeps working against a database built from the migrations, and breaks
# only for whoever set theirs up from schema.sql.
#
# Usage, from the repository root:
#   bash supabase/tool/build_schema.sh
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
migrations="$root/supabase/migrations"
out="$root/supabase/schema.sql"

{
  cat <<'HEADER'
-- ===========================================================================
-- What's Cooking? — complete schema
--
-- HOW TO USE
--   Supabase dashboard → SQL Editor → New query → paste this whole file → Run.
--   Safe to re-run: everything is create-if-not-exists or create-or-replace.
--
-- Generated by concatenating supabase/migrations/ in order. Edit the
-- migrations, not this file, then regenerate with:
--   supabase/tool/build_schema.sh
--
-- Verify afterwards with supabase/verify.sql.
-- ===========================================================================

HEADER

  for file in "$migrations"/*.sql; do
    printf '\n-- ==================== %s ====================\n\n' "$(basename "$file")"
    cat "$file"
  done
} > "$out"

echo "Wrote $out from $(ls -1 "$migrations"/*.sql | wc -l | tr -d ' ') migrations."
